language: c

os:
  - linux
  - osx

before_install: |
  case $TRAVIS_OS_NAME in
  linux)
    sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
    echo "deb http://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
    sudo apt-get update
    ;;
  osx)
    brew update
    ;;
  esac

install: |
  case $TRAVIS_OS_NAME in
  linux)
    sudo apt-get install crystal
    ;;
  osx)
    brew install crystal-lang
    ;;
  esac

before_script: |
  make
  bin/shards install
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
  git config --global column.ui always

script:
  - make test
