language: crystal

os:
  - linux
  - osx

before_script:
  - make
  - bin/shards install
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script:
  - make test
