language: crystal

os:
  - linux

before_script: |
  make
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
  git config --global column.ui always

script:
  - make test
  - crystal tool format --check src spec
