version = 1

# All original code in this repository is licensed under Apache 2.0.
[[annotations]]
path = ["**"]
SPDX-FileCopyrightText = "Copyright 2012-2026 Manas Technology Solutions."
SPDX-License-Identifier = "Apache-2.0"

# Unset license information for vendored libraries ("shards"). They either
# provide their own information or there's a specific section in this file.
[[annotations]]
path = ["lib/*/**"]
