name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 1" # Every monday 6 AM

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: [latest, nightly]
        include:
          - os: windows-latest
            crystal: nightly
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global column.ui always
          git config --global core.autocrlf false

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Mercurial
        run: pip install mercurial

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Install Fossil
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install fossil

      - name: Install Fossil
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install fossil

      - name: Install Fossil
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install fossil

      - name: Download source
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Run specs
        run: make test

      - name: Check formatting
        run: crystal tool format --check src spec

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Build manpages
        uses: Analog-inc/asciidoctor-action@v1.3.1
        with:
          shellcommand: "make -B manpages SOURCE_DATE_EPOCH=\"$(date +%s --utc --date \"$(grep -m1 -o -E 'Date: .*' man/shard.yml.5 | cut -d' ' -f2)\")\""
      - name: Ensure no changes
        run: git diff --exit-code
